[package]
name = "bs2"
version = "0.0.1"
edition = "2024"
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]

[dependencies]
libloading = "0.9.0"
winapi = { version = "0.3", features = [
    "libloaderapi",
    "stringapiset",
    "processenv",
    "minwindef",
] }
