name: Build Installer
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build installer
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Restore Rust cache
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: release
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build project
        run: cargo build --release

      - name: Compile Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer/installer.iss
          options: /O+

      - name: Sign Installer
        uses: mscrivo/signtool-code-sign@v1
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          cert-password: '${{ secrets.CERTPASSWORD }}'
          cert-sha1: '${{ secrets.CERTHASH }}'
          cert-description: 'Installer for BS2'
          folder: 'installer/Output'
          timestamp-server: 'http://timestamp.digicert.com'
